### ISSUE TITLE
i think roblox hates us

### ISSUE THREAD

**Issue by BoogieHasFun** [1011025m/RobloxHomePatcher#4]
am getting error:
`RobloxPlayerBeta.exe
Target bytes set 1 of 3 is not found.
Target bytes set 2 of 3 is not found.
Target bytes set 3 of 3 is not found.
3 failures occured when patching.
Press Enter to quit
`

**Comment by BoogieHasFun** [comment]
it seems https://github.com/Windows81/Roblox-Home-Patcher/tree/main worked as well as running it as admin somewhere else.

**Comment by 1011025m** [comment]
> am getting error: `RobloxPlayerBeta.exe Target bytes set 1 of 3 is not found. Target bytes set 2 of 3 is not found. Target bytes set 3 of 3 is not found. 3 failures occured when patching. Press Enter to quit `

Huh? Was the script patching the wrong file? Why is it saying RobloxPlayerBeta.exe??? It's not supposed to do that and nothing in the script points to anything with that filename???????


> it seems https://github.com/Windows81/Roblox-Home-Patcher/tree/main worked as well as running it as admin somewhere else.

This is just a fork of this repository, doesn't actually have any functional difference. (I think)
