### ISSUE TITLE
It got patched?

### ISSUE THREAD

**Issue by Ygor6889** [1011025m/RobloxHomePatcher#5]
I tried to use today and it did said "patch done" but when I open Roblox via browser it just opens the crappy app
![image](https://user-images.githubusercontent.com/109400625/200963203-53e9e27f-94d4-4414-a885-facb55b0b079.png)

**Comment by 1011025m** [comment]
Yup, they patched it by removing support for the --play flag entirely. There is no easy way around this - only way I could think of is preventing the `RobloxPlayerBeta.exe` from launching into the in-app homepage, That requires looking into the binary file though, and if anything it'll be risky once they introduce Hyperion in the future.

**Comment by 1011025m** [comment]
Fixed temporarily with fcacd4960d2f6ae3e2351e8cd87865233486b6a5.

**Comment by DaEnder** [comment]
> I tried to use today and it did said "patch done" but when I open Roblox via browser it just opens the crappy app ![image](https://user-images.githubusercontent.com/109400625/200963203-53e9e27f-94d4-4414-a885-facb55b0b079.png)

"Crappy app" KILL YOURSELF
