### ISSUE TITLE
unfortunately patched

### ISSUE THREAD

**Issue by Zoardedz** [1011025m/RobloxHomePatcher#6]
all in the title, when renaming the mobile.rbxl file roblox itself crashes. assuming that it's a vital roblox file.

**Comment by Ygor6889** [comment]
Still working fine here

**Comment by 1011025m** [comment]
Cannot reproduce. Tested with a new installation of Roblox.

Make sure you are passing the --app flag to `RobloxBetaPlayer.exe` or else the executable won't launch at all.

**Comment by 1011025m** [comment]
If you're willing to provide me the steps you've taken and explain a bit more about your situation, it might help more.

**Comment by Zoardedz** [comment]
i'll see the steps

**Comment by Zoardedz** [comment]
actually, yes it crashes because mobile.rbxl is missing, i'll see if the NON legacy method fixes it

**Comment by 1011025m** [comment]
Resolved, user error.
